//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public account()
        {
            this.adminaccounts = new HashSet<adminaccount>();
            this.clientaccounts = new HashSet<clientaccount>();
            this.storeaccounts = new HashSet<storeaccount>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string AccountType { get; set; }
    
        public virtual ICollection<adminaccount> adminaccounts { get; set; }
        public virtual ICollection<clientaccount> clientaccounts { get; set; }
        public virtual ICollection<storeaccount> storeaccounts { get; set; }
    }
}
