//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientaccount
    {
        public clientaccount()
        {
            this.tickets = new HashSet<ticket>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdACCOUNT { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Avartar { get; set; }
        public string Description { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
    
        public virtual account account { get; set; }
        public virtual ICollection<ticket> tickets { get; set; }
    }
}
